### ISSUE TITLE
Registry for SAMD51

### ISSUE THREAD

**Issue by vslinuxdotnet** [gjt211/SAMD21-Reset-Cause#1]
Hello,
There is a registry for SAMD51 ?

I try to define it from SAM21 without sucess:
`#define REG_PM_RCAUSE              (0x40000438U)`

Thank you

**Comment by gjt211** [comment]
Hi @vslinuxdotnet 
I dont have any experience with the SAMD51, but if you look in the datasheet, the RCAUSE register contains the information you need.
You might need to write the defines for each of the bits as I don't know if there is an Arduino library for the SAMD51.
The relevant register is located in the datasheet on page 186.
[http://ww1.microchip.com/downloads/en/DeviceDoc/SAM_D5xE5x_Family_Data_Sheet_DS60001507F.pdf](url)
